In [3]:
import numpy as np

In [10]:
data = [[10,12,9,5],[45,78,3,14]]
print (data)


[[10, 12, 9, 5], [45, 78, 3, 14]]


In [7]:
myArr = np.array(data) # creation of numpy array
print (myArr)

[[10 12  9  5]
 [45 78  3 14]]


In [8]:
myArr.__class__

numpy.ndarray

In [6]:
myArr.ndim

2

In [7]:
myArr.shape

(2, 4)

In [8]:
myArr.dtype

dtype('int32')

In [6]:
myNewArr = np.arange(15).reshape(3,5)
print (myNewArr)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


In [11]:
print (myNewArr[1][3])

8


In [30]:
random.seed(32)
randomArr = np.random.randn(6,3)
print (randomArr)

[[ 0.93885608 -1.14036483 -0.15915027]
 [-2.32053141  0.44714035 -0.53573429]
 [-1.01823557  1.15067991 -1.2589258 ]
 [ 2.03786311  0.00244294  1.07079251]
 [-0.91248134 -0.62753126  1.86325908]
 [-0.5013921   0.4235699  -0.23685288]]


In [41]:
np.log(randomArr)

/home/rk/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in log
  """Entry point for launching an IPython kernel.


array([[-0.06309308,         nan,         nan],
       [        nan, -0.80488275,         nan],
       [        nan,  0.14035299,         nan],
       [ 0.71190176, -6.01455108,  0.06839904],
       [        nan,         nan,  0.62232715],
       [        nan, -0.85903673,         nan]])

In [42]:
data = [[10,12,9,5],[45,78,3,14]]
print (data)
myArr1 = np.array(data)
print (myArr1)

[[10, 12, 9, 5], [45, 78, 3, 14]]
[[10 12  9  5]
 [45 78  3 14]]


In [43]:
data = [[11,1,91,35],[5,8,13,4]]
print (data)
myArr2 = np.array(data)
print (myArr2)

[[11, 1, 91, 35], [5, 8, 13, 4]]
[[11  1 91 35]
 [ 5  8 13  4]]


In [40]:
myArr3 = np.add (myArr1, myArr2)
print (myArr3)

[[ 21  13 100  40]
 [ 50  86  16  18]]
